config/routes.rb
Rails.application.routes.draw do

	get 'search/(:query)', controller: 'static_pages', action: 'buscar'
	get 'users/new'

	resources :users

	get 'users(/id/:id)/s', controller: 'users', action: 'solicitar_premium'
	get 'users(/id/:id)/p', controller: 'users', action: 'autorizar_premium'
	get 'users(/id/:id)/r', controller: 'users', action: 'remover_premium'

	resources :bids

	resources :entries

	resources :blocks, :path => 'blocks'
	get 'blocks(/fecha/:fecha)(/rid/:residence_id)', controller: 'blocks', action: 'show'

	get 'blocks(/id/:id)(/uid/:user_id)', controller: 'blocks', action: 'salir_subasta'

	get 'sessions/new'
	root 'static_pages#home'


	get '/signup',  to:
	 'users#new'

	get 'admins/new', to:
	'admins#new'

  get '/signup', to:
  'admins#new'


  delete '/logout',  to:
  'sessions#destroy'


  post '/signup', to:
  'admins#create'

  post 'entries/new', to:
  'entries#new'


	  get '/login', to:
	  'sessions#new'

	  post '/login', to:
	  'sessions#create'

		post '/logout', to:
	  'sessions#destroy'


  resources :admins
  resources :residences
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/new.html.erb
<% provide(:title , 'Nuevo administrador') %>

<% if logged_in_admin? %>
	<div class='row text-center'>
		<div class="col-3"></div>
		<div class="col-6">
			<div class="card rounded-0">
				<div class="card-header">
					<h3>Crear administrador</h3>
				</div>
				<%= form_for(@admin) do |f| %>
					<%= render 'shared/error_messages', user: @admin %>
					<%= f.label :codigo %>
					<%= f.text_field :codigo, class: 'form-control rounded-0', required:true %>
					<%= f.submit "Crear un nuevo administrador", class:"btn btn-primary rounded-0" %>
				<% end %>
			</div>
		</div>
	</div>
<% else %>
	Acceso denegado :)
<% end %>

app/views/admins/show.html.erb
<% provide(:title , 'Panel de administracion') %>

<div class="container">

	<h1>Panel de administracion</h1>

	<table class='table'>
		<tbody>
			<tr>
				<td>
					<a href="/users" class="btn btn-outline-primary rounded-0 col-12">Lista de Usuarios</a>
				</td>
				<td>
					<%= link_to "Nuevo administrador", new_admin_path, method: :get, class:'btn btn-outline-primary rounded-0 col-12' %>
				</td>
			</tr>
			<tr>
				<td>
					<a href="/residences" class="btn btn-outline-primary rounded-0 col-12">Lista de Residencias</a>
				</td>
				<td>
					<a href="/residences/new" class="btn btn-outline-primary rounded-0 col-12">Nueva Residencia</a>
				</td>
			</tr>
		</tbody>
	</table>

</div>