config/routes.rb
Rails.application.routes.draw do

	get 'search/(:query)', controller: 'static_pages', action: 'buscar'
	get 'users/new'

	resources :users

	get 'users(/id/:id)/s', controller: 'users', action: 'solicitar_premium'
	get 'users(/id/:id)/p', controller: 'users', action: 'autorizar_premium'
	get 'users(/id/:id)/r', controller: 'users', action: 'remover_premium'

	resources :bids

	resources :entries

	resources :blocks, :path => 'blocks'
	get 'blocks(/fecha/:fecha)(/rid/:residence_id)', controller: 'blocks', action: 'show'

	get 'blocks(/id/:id)(/uid/:user_id)', controller: 'blocks', action: 'salir_subasta'

	get 'sessions/new'
	root 'static_pages#home'


	get '/signup',  to:
	 'users#new'

	get 'admins/new', to:
	'admins#new'

  get '/signup', to:
  'admins#new'


  delete '/logout',  to:
  'sessions#destroy'


  post '/signup', to:
  'admins#create'

  post 'entries/new', to:
  'entries#new'


	  get '/login', to:
	  'sessions#new'

	  post '/login', to:
	  'sessions#create'

		post '/logout', to:
	  'sessions#destroy'


  resources :admins
  resources :residences
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/block.rb
class Block < ApplicationRecord

	belongs_to :residence
	has_many :entries
	has_many :bids

	validates :precio, numericality: { greater_than_or_equal_to: 0, message: ' debe ser mayor o igual a cero.' }
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
	before_action :set_block, only: [:show, :edit, :update, :destroy]
	before_action :logged_in, only: [:edit, :update, :show, :destroy, :new]

	# GET /blocks
	# GET /blocks.json
	def index
		@blocks = Block.all
	end

	# GET /blocks/1
	# GET /blocks/1.json
	def show
	end

	# GET /blocks/new
	def new
		@block = Block.new
	end

	# GET /blocks/1/edit
	def edit
	end

	# POST /blocks
	# POST /blocks.json
	def create
		@block = Block.new(block_params)

		respond_to do |format|
			if @block.save
				format.html { redirect_to @block, notice: 'El bloque fue creado correctamente.' }
				format.json { render :show, status: :created, location: @block }
			else
				format.html { render :new }
				format.json { render json: @block.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /blocks/1
	# PATCH/PUT /blocks/1.json
	def update
		respond_to do |format|
			if @block.update(block_params)
				format.html { redirect_to @block, notice: 'El bloque fue actualizado correctamente.' }
				format.json { render :show, status: :ok, location: @block }
			else
				format.html { redirect_to @block, notice: @block.errors.full_messages.first}
				format.json { render json: @block.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /blocks/1
	# DELETE /blocks/1.json
	def destroy
		@block.destroy
		respond_to do |format|
			format.html { redirect_to blocks_url, notice: 'Block was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	def salir_subasta
		@block = Block.find(params[:id])
		@entrada = @block.entries.where(:user_id => (params[:user_id].to_i)).first
		@pujas = @entrada.bids
		@pujas.each do |pujas|
			pujas.destroy
		end
		@entrada.destroy
		respond_to do |format|
			format.html { redirect_to @block, notice: 'Has salido de la subasta' }
			format.json { head :no_content }
		end
	end

	private

	def logged_in
		unless logged_in_user? || logged_in_admin?
			flash[:danger] = "Please log in."
			redirect_to login_url
		end
	end
	# Use callbacks to share common setup or constraints between actions.
	def set_block
		if (Residence.find_by_id(params[:residence_id]) != nil)
			@block = Block.where(:fecha => params[:fecha],
										:residence_id => params[:residence_id]).first_or_create do |bloque|
				bloque.precio = 0
				bloque.estado = 0
			end
		else
			@block = Block.find(params[:id])
		end
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def block_params
		params.require(:block).permit(:fecha, :precio, :estado, :adjudicado, :residence_id, :adjudicadoid)
	end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/_blockhotsale.html.erb
<% @adjudicado = (block.adjudicado != '' && block.adjudicado != nil && block.adjudicadoid != nil) %>

<h5>Precio del bloque <span class="badge badge-success"><%= block.precio %></span></h5>

<% if logged_in_admin? %>

	<% if @adjudicado %>

		<h5>Bloque adjudicado a <%= block.adjudicado %></h5>

	<% else %>

		<%= form_for(block) do |formulario| %>
			<div class="input-group">
				<%= formulario.hidden_field :estado, :value => 0 %>
				<div class="input-group-append p-0 m-0 col-12">
					<%= formulario.submit "Cerrar Hotsale", class: 'btn btn-primary rounded-0' %>
				</div>
			</div>
		<% end %>

	<% end %>

<% end %>

<% if logged_in_user? %>

	<% if @adjudicado %>

		<h5>Bloque adjudicado!</h5>

	<% else %>

		<%= form_for(block) do |formulario| %>
			<div class="input-group">
				<%= formulario.hidden_field :adjudicadoid, value: current_user.id %>
				<%= formulario.hidden_field :adjudicado, value: current_user.email %>
				<div class="input-group-append p-0 m-0 col-12">
					<%= formulario.submit "Adjudicarme este bloque!", class: 'btn btn-primary rounded-0' %>
				</div>
			</div>
		<% end %>

	<% end %>

<% end %>

app/views/blocks/_blocknormal.html.erb
<% if((block.fecha << 6) <=> Date.today) > 0 %>

	<!-- Periodo de subasta, aun no se llogo a los 6 meses. -->

	<% if logged_in_admin? %>

		<% if !(block.adjudicado == '' || block.adjudicado == nil) %>

			<h5>Bloque adjudicado a <%= block.adjudicado %></h5>

		<% else %>

			<div class="alert alert-warning" role="alert">
				La creacion de hotsale se encontrara disponible a partir del dia <%= block.fecha << 6 %>.
			</div>

			<%= form_for(block) do |b| %>
				<div class="input-group">
					<%= b.text_field :precio, class: 'form-control rounded-0 col-6' %>
					<%= b.hidden_field :estado, :value => 1 %>
					<div class="input-group-append p-0 m-0 col-6">
						<%= b.submit "Crear subasta", class: 'btn btn-primary rounded-0' %>
					</div>
				</div>
			<% end %>

		<% end %>

		<h5 class="mt-3">Participantes</h3>
		<div class="list-group" style="height:200px; overflow-y:scroll;">
			<% block.entries.each do |entry|%>
				<div class="list-group-item">
					<small><%= entry.email %></small>
				</div>
			<%end%>
		</div>

	<% end %>

	<% if logged_in_user? %>

		<% if !(block.adjudicado == '' || block.adjudicado == nil) %>

			<h5>Bloque adjudicado!</h5>

		<% else %>
			<% if current_user.user_configs.esPremium %>

				<% if current_user.user_configs.creditos > 0 %>
				<!-- Falta lo de los creditos-->
				<%= form_for(block) do |formulario| %>

					<%= formulario.hidden_field :adjudicado, :value => current_user.email %>
					<%= formulario.hidden_field :adjudicado_id, :value => current_user.id %>

					<div class="input-group-append p-0 m-0 col-6">
						<%= formulario.submit "Adjudicarme este bloque!", class: 'btn btn-success rounded-0' %>
					</div>
					<br>

				<% end #formulario %>

				<%else #creditos%>

				<%end%>

		<% else %>

			<% if block.entries.where(:email => current_user.email).first == nil %>

				<%= form_for(Entry.new) do |formulario| %>
					<div class="input-group">
						<%= formulario.hidden_field :block_id, :value => block.id %>
						<%= formulario.hidden_field :user_id, :value => current_user.id %>
						<%= formulario.hidden_field :email, :value => current_user.email %>
						<div class="input-group-append p-0 m-0 col-6">
							<%= formulario.submit "Participar", class: 'btn btn-secondary rounded-0' %>
						</div>
					</div>
				<% end %>


			<% else %>

				<a href="/blocks/id/<%=block.id%>/uid/<%=current_user.id%>" class= 'btn btn-danger col-6 rounded-0'>Salir Subasta</a>

			<% end %>
			<% end %>

		<% end %>

	<% end %>

<% else %>

	<!-- Periodo de hotsale, ya se entro en los 6 meses. -->

	<% if logged_in_admin? %>

		<% if !(block.adjudicado == '' || block.adjudicado == nil) %>

			<h5>Bloque adjudicado a <%= block.adjudicado %></h5>

		<% else %>

			<div class="alert alert-warning" role="alert">
				La subasta ya no se encuentra disponible.
			</div>

			<%= form_for(block) do |b| %>
				<div class="input-group">
					<%= b.text_field :precio, class: 'form-control rounded-0 col-6' %>
					<%= b.hidden_field :estado, :value => 2 %>
					<div class="input-group-append p-0 m-0 col-6">
						<%= b.submit "Crear hotsale", class: 'btn btn-secondary rounded-0' %>
					</div>
				</div>
			<% end %>

		<% end %>

	<% end %>

	<% if logged_in_user? %>

		<% if !(block.adjudicado == '' || block.adjudicado == nil) %>

			<h5>Bloque adjudicado!</h5>

		<% else %>

			<div class="alert alert-warning" role="alert">
				La subasta ya no se encuentra disponible.
			</div>

		<% end %>

	<% end %>

<%end%>

app/views/blocks/_blocksubasta.html.erb
<% if logged_in_admin? %>

	<%= form_for(block) do |b| %>
		<div class="input-group">
			<%= b.hidden_field :estado, :value => 0 %>
			<% if block.bids.order(valor: :desc).first != nil %>
			<%= b.hidden_field :adjudicado, :value => block.bids.order(valor: :desc).first.entry.email %>
			<%end%>
			<div class="input-group-append p-0 m-0 col-6">
				<%= b.submit "Cerrar Subasta", class: 'btn btn-primary rounded-0' %>
			</div>
		</div>
	<% end %>

	<h5 class="mt-3">Participantes</h3>
	<div class="list-group" style="height:200px; overflow-y:scroll;">
		<% block.entries.each do |entry|%>
			<div class="list-group-item">
				<small><%= entry.email %></small>
			</div>
		<%end%>
	</div>

	<h5 class="mt-3">Pujas (piso <span class="badge badge-success"><%= block.precio %></span>)</h3>
	<div class="list-group" style="height:200px; overflow-y:scroll;">
		<% block.bids.order(valor: :desc).each do |bid|%>
			<div class="list-group-item">
				<small><%= bid.entry.email %> <span class="badge badge-success"><%= bid.valor %></span></small>
			</div>
		<%end%>
	</div>

<% end %>

<% if logged_in_user? %>

	<%= form_for(Bid.new) do |formulario| %>
		<div class="input-group">
			<%= formulario.text_field :valor, class: 'form-control rounded-0 col-5 m-0', placeholder: 'monto', oninput:'check(this)' %>
			<%= formulario.hidden_field :block_id, :value => block.id %>
			<%= formulario.hidden_field :user_id, :value => current_user.id %>
			<%= formulario.hidden_field :email, :value => current_user.email %>
			<div class="input-group-append p-0 m-0 col-2">
				<%= formulario.submit "Pujar!", class: 'btn btn-success rounded-0' %>
			</div>
		</div>
	<% end %>

		<% if block.entries.where(:email => current_user.email).first != nil %>
			<a href="/blocks/id/<%=block.id%>/uid/<%=current_user.id%>" class= 'btn btn-danger col-6 rounded-0'>Salir Subasta</a>
		<% end %>

	<script>
		function check(input) {
			<% if block.bids.order(valor: :desc).first != nil %>
			if ((input.value <= <%= block.precio%>) || (input.value <= <%= block.bids.order(valor: :desc).first.valor %> )) {
			<% else %>
			if ((input.value <= <%= block.precio%>)) {
			<% end %>
				input.setCustomValidity('La puja debe ser mayor a la ultima realizada, o al piso.');
			} else {
				// input is fine -- reset the error message
				input.setCustomValidity('');
			}
		}
	</script>

	<h5 class="mt-3">Pujas (piso <span class="badge badge-success"><%= block.precio %></span>)</h3>
	<div class="list-group" style="height:200px; overflow-y:scroll;">
		<% block.bids.order(valor: :desc).each do |bid|%>
			<div class="list-group-item">
				<small><%= bid.entry.email %> <span class="badge badge-success"><%= bid.valor %></span></small>
			</div>
		<%end%>
	</div>

<% end %>

app/views/blocks/_form.html.erb
<%= form_with(model: block, local: true) do |form| %>
  <% if block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% block.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :adjudicado %>
    <%= form.text_field :adjudicado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blocks/index.html.erb
<% if logged_in_admin? %>
<p id="notice"><%= notice %></p>

<h1>Blocks</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Adjudicado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blocks.each do |block| %>
      <tr>
        <td><%= block.fecha %></td>
        <td><%= block.adjudicado %></td>
        <td><%= link_to 'Show', block %></td>
        <td><%= link_to 'Edit', edit_block_path(block) %></td>
        <td><%= link_to 'Destroy', block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Block', new_block_path %>
<% end %>

app/views/blocks/show.html.erb
<% case @block.estado %>
<% when 0 #bloque normal %>

	<%= render 'blocknormal', block: @block %>

<% when 1 #bloque en subasta %>

	<%= render 'blocksubasta', block: @block %>

<% when 2 #bloque en hotsale %>

	<%= render 'blockhotsale', block: @block %>

<% end %>

<% parent_layout "residencia" %>