config/routes.rb
Rails.application.routes.draw do

	get 'search/(:query)', controller: 'static_pages', action: 'buscar'
	get 'users/new'

	resources :users

	get 'users(/id/:id)/s', controller: 'users', action: 'solicitar_premium'
	get 'users(/id/:id)/p', controller: 'users', action: 'autorizar_premium'
	get 'users(/id/:id)/r', controller: 'users', action: 'remover_premium'

	resources :bids

	resources :entries

	resources :blocks, :path => 'blocks'
	get 'blocks(/fecha/:fecha)(/rid/:residence_id)', controller: 'blocks', action: 'show'

	get 'blocks(/id/:id)(/uid/:user_id)', controller: 'blocks', action: 'salir_subasta'

	get 'sessions/new'
	root 'static_pages#home'


	get '/signup',  to:
	 'users#new'

	get 'admins/new', to:
	'admins#new'

  get '/signup', to:
  'admins#new'


  delete '/logout',  to:
  'sessions#destroy'


  post '/signup', to:
  'admins#create'

  post 'entries/new', to:
  'entries#new'


	  get '/login', to:
	  'sessions#new'

	  post '/login', to:
	  'sessions#create'

		post '/logout', to:
	  'sessions#destroy'


  resources :admins
  resources :residences
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/layouts_helper.rb
# Place this in app/helpers/layouts_helper.rb
module LayoutsHelper
	def parent_layout(layout)
	  @view_flow.set(:layout, output_buffer)
	  output = render(:file => "layouts/#{layout}")
	  self.output_buffer = ActionView::OutputBuffer.new(output)
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<head>

		<title>HSH - <%= yield :title %></title>

		<%= csrf_meta_tags %>
    	<%= csp_meta_tag %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	</head>

	<body>

		<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    		<a href="/" class="my-0 mr-md-auto font-weight-normal">
				<%= image_tag("HSH-Text.svg", :class => 'p-0 m-0', :width => '250px') %>
			</a>
			<nav class="my-2 my-md-0 mr-md-3">
				<% if logged_in_admin? %>
					<%= link_to "Panel de administracion", current_admin, method: :get, class:'btn btn-outline-primary rounded-0' %>
					<%= link_to "Cerrar sesion", logout_path, method: :delete, class:'btn btn-outline-primary rounded-0' %>
				<% else %>
					<% if logged_in_user? %>
						<%= link_to "Cerrar sesion", logout_path, method: :delete, class:'btn btn-outline-primary rounded-0' %>
						<%= link_to "Ver perfil", current_user, method: :get, class:'btn btn-outline-primary rounded-0' %>
					<% else %>
						<a class="btn btn-outline-primary rounded-0" href="/login">Iniciar Sesion</a>
						<%= link_to "Registrarse!", signup_path, method: :get, class:'btn btn-outline-primary rounded-0' %>
					<% end %>
				<% end %>
			</nav>
    	</div>

    	<div class="container">

			<%= yield %>

    		<footer class="pt-4 my-md-5 pt-md-5 border-top">
        		<div class="row">
          			<div class="col-12 col-md">
					  	<%= image_tag("HSH-Logo.svg", :class => 'p-0 m-0', :width => '48px') %>
            			<small class="d-block mb-3 text-muted">&copy; 2018</small>
          			</div>
          			<!--<div class="col-6 col-md">
            			<h5>Features</h5>
            			<ul class="list-unstyled text-small">
              				<li><a class="text-muted" href="#">Cool stuff</a></li>
              				<li><a class="text-muted" href="#">Random feature</a></li>
							<li><a class="text-muted" href="#">Team feature</a></li>
							<li><a class="text-muted" href="#">Stuff for developers</a></li>
							<li><a class="text-muted" href="#">Another one</a></li>
							<li><a class="text-muted" href="#">Last time</a></li>
            			</ul>
          			</div>
          			<div class="col-6 col-md">
            			<h5>Resources</h5>
            			<ul class="list-unstyled text-small">
							<li><a class="text-muted" href="#">Resource</a></li>
							<li><a class="text-muted" href="#">Resource name</a></li>
							<li><a class="text-muted" href="#">Another resource</a></li>
							<li><a class="text-muted" href="#">Final resource</a></li>
            			</ul>
          			</div>
          			<div class="col-6 col-md">
            			<h5>About</h5>
            			<ul class="list-unstyled text-small">
							<li><a class="text-muted" href="#">Team</a></li>
							<li><a class="text-muted" href="#">Locations</a></li>
							<li><a class="text-muted" href="#">Privacy</a></li>
							<li><a class="text-muted" href="#">Terms</a></li>
            			</ul>
          			</div>-->
        		</div>
      		</footer>

		</div>
	</body>
</html>

app/views/layouts/header.html.erb
     <nav class="navbar navbar-dark bg-dark">
           <a class="navbar-brand" href="#">Home Swich Home</a>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
           </button>

           <div class="collapse navbar-collapse" id="navbarsExample01">
             <ul class="navbar-nav mr-auto">
               <li class="nav-item active">
                 <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
               </li>
               <li class="nav-item">
                 <a class="nav-link" href="#">Link</a>
               </li>
               <li class="nav-item">
                 <a class="nav-link disabled" href="#">Disabled</a>
               </li>
               <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                 <div class="dropdown-menu" aria-labelledby="dropdown01">
                   <a class="dropdown-item" href="#">Action</a>
                   <a class="dropdown-item" href="#">Another action</a>
                   <a class="dropdown-item" href="#">Something else here</a>
                 </div>
               </li>
             </ul>
             <form class="form-inline my-2 my-md-0">
               <input class="form-control" type="text" placeholder="Search" aria-label="Search">
             </form>
           </div>
         </nav>

app/views/layouts/residencia.html.erb
<% if @residence != nil %>
	<% @var = @residence %>
<% else %>
	<% @var = @block.residence %>
<% end %>

<div class="container">
	<div class="row border">
		<div class="col-6 p-0 m-0">
			<div class="card border-0 rounded-0">
				<div class="card-header m-0 border-0 rounded-0">
					<h3 class="m-0 p-0">
						<div class="row">
							<a href="<%= @block != nil ? residence_path(@var) : '/' %>" class="btn btn-outline-primary ml-2 rounded-0">Atras</a>
							<span class="align-middle mt-auto mb-auto ml-2"><%= @var.nombre %></span>
							<% if logged_in_admin? %>
								<%= link_to 'Modificar', edit_residence_path(@var), class: 'btn btn-warning ml-md-auto mr-2 rounded-0 m-0', style:'height: 100% !important;' %>
								<%= link_to 'Eliminar', @var, method: :delete, class: 'btn btn-danger mr-2 rounded-0', data: { confirm: 'Estas seguro?' } %>
							<% end %>
						</div>
					</h3>
				</div>
				<img class="card-img-top rounded-0" style="width: 100% !important;" src="<%= @var.img_link %>">
			</div>
		</div>
		<div class="col-6 p-0 m-0">
			<ul class="list-group list-group-flush">
				<li class="list-group-item">
					<h5><span class="badge badge-info mr-3"><%= notice %></span></h5>
					<p><%= @var.desc %></p>
					<p class="font-weight-bold text-capitalize m-0">
						<%= @var.direccion %><span class="text-muted">, <%= @var.ciudad %>, <%= @var.partido %>, <%= @var.provincia %></span>
					</p>
				</li>
				<li class="list-group-item">
					<%= yield %>
				</li>
			</ul>
		</div>
	</div>
</div>